url: "https://peachparfait.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "parfait9"
description: >- # this means to ignore newlines until "baseurl:"
  ぱふぇ（あじのり）のサイトです
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:categories/:title

plugins:
  - jekyll-feed
markdown: kramdown
lang: ja-jp
theme: "minima"